import os
import json
import logging
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from utils.progress import show_progress

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

# Sample corrections mapping (add more as needed)
corrections = {
    "Ademola Lukman": "Ademola Lookman",
    "Adi Emi": "Adeyemi",
    "Adrielle Rabiot": "Adrien Rabiot",
    "Adrienne Rabiot": "Adrien Rabiot",
    "Adrienne Rabiò": "Adrien Rabiot",
    "Andrea Rabiou": "Adrien Rabiot",
    "Alexander Arnault": "Trent Alexander-Arnold",
    "Alfonso Davis": "Alphonso Davies",
    "Alfonso Devis": "Alphonso Davies",
    "Amadialo": "Amad Diallo",
    "Amadija": "Amad Diallo",
    "Amadija Law": "Amad Diallo",
    "Amadou Onaná": "Amadou Onana",
    "Amaduanana": "Amadou Onana",
    "Anso Fatih": "Ansu Fati",
    "Anzou Fati": "Ansu Fati",
    "Anzu": "Ansu Fati",
    "Anzif Lick": "Ansu Fati",
    "Anziflique": "Ansu Fati",
    "Anzufati": "Ansu Fati",
    "Anthony Marzial": "Anthony Martial",
    "Anthony Marziale": "Anthony Martial",
    "Benjamin Cesco": "Benjamin Šeško",
    "Benjamin Schesco": "Benjamin Šeško",
    "Benjaminsche Schesco": "Benjamin Šeško",
    "Blavich": "Dušan Vlahović",
    "Blauvić": "Dušan Vlahović",
    "Calafioli": "Riccardo Calafiori",
    "Calafiore": "Riccardo Calafiori",
    "Ashraf Akimi": "Achraf Hakimi",
    "Akimi": "Achraf Hakimi",
    "Al Naser": "Al Nassr",
    "Al Nasser": "Al Nassr",
    "Al-Nassar": "Al Nassr",
    "Al-Nasser": "Al Nassr",
    "Alnasser": "Al Nassr",
    "Al-Akhli": "Al-Ahli",
    "Al-Ali": "Al-Ahli",
    "Al-Illal": "Al Hilal",
    "Alilal": "Al Hilal",
    "Arlilal": "Al Hilal",
    "Barca": "FC Barcelona",
    "Barça": "FC Barcelona",
    "Barmout": "Bournemouth",
    "Barmouth": "Bournemouth",
}
corrections.update({
    "Artheta": "Arteta",
    "Alach Lee": "Achraf Hakimi",
    "Alachli": "Achraf Hakimi",
    "Andrea Bertha": "Andrea Berta",
    "Andre Berta": "Andrea Berta",
    "Alexander Arnold": "Trent Alexander-Arnold",
    "Alexander-Arnold": "Trent Alexander-Arnold",
    "Andriy Lunin": "André Lunin",
    "Andre Lunin": "André Lunin",
    "Andreonana": "Andre Onana",
    "Andrick": "Endrick",
    "Aron Anselmino": "Anselmino",
    "Aron Arselmino": "Anselmino",
    "Barmout": "Bournemouth",
    "Barmouth": "Bournemouth",
    "Bayer Leberkusen": "Bayer Leverkusen",
    "Bayer-Levercusan": "Bayer Leverkusen",
    "Bayer Leuverkusen": "Bayer Leverkusen",
    "Ancico": "Ancelotti",
    "Anciflik": "Ansiflik",
    "Ansiflick": "Ansiflik",
    "Ansif Lick": "Ansiflik",
    "Antonio Conti": "Antonio Conte",
    "Asensio": "Marco Asensio",
    "Asencio": "Marco Asensio",
    "Axel Dizazie": "Axel Disasi",
    "Airallo": "Airolo",  # Assuming these are meant to be the same
    "Calulu": "Pierre Kalulu",
    "Casadei": "Cesare Casadei",
    "Casa Dei": "Cesare Casadei",
    "Carnaccio": "Alejandro Garnacho",
    "Carny": "Alejandro Garnacho",
    "Carlo": "Carlo Ancelotti",
    "Carlo Cialotti": "Carlo Ancelotti",
    "Calafiori": "Riccardo Calafiori",
})
corrections.update({
    "Cesko": "Cesco",
    "Chabi": "Xavi",
    "Chabi Alonso": "Xabi Alonso",
    "Chabiel": "Xabi Alonso",
    "Chaloba": "Chalobah",
    "Chalobar": "Chalobah",
    "Chavi": "Xavi",
    "Chavi Simons": "Xavi Simons",
    "Chelsea Atletico": "Chelsea",
    "Chelsea Football Club": "Chelsea",
    "Chelsea Liverpool": "Chelsea",
    "Chelsea Tottenham": "Chelsea",
    "Cherokee": "Cherki",
    "Cherqui": "Cherki",
    "Chesny": "Kepa Arrizabalaga",
    "Chicago Fire": "Chicago Fire FC",
    "Chouamanie": "Aurélien Chouameni",
    "Choukwemeca": "Karny Chukwameka",
    "Christofran Kunku": "Christopher Nkunku",
    "Christopher Kunku": "Christopher Nkunku",
    "Ciavi": "Xavi",
    "Ciavi Simons": "Xavi Simons",
    "Ciavielonso": "Xabi Alonso",
    "Cicchi Begiristain": "Txiki Begiristain",
    "Cido Bimartin": "Cido Bamba",
    "City": "Manchester City",
    "Clement Lenglet": "Clément Lenglet",
    "Cologne Monty": "1. FC Köln",
    "Colomoni": "Colomoni",
    "Coman": "Kingsley Coman",
    "Conor Gallagher": "Conor Gallagher",
    "Conte": "Antonio Conte",
    "Coppa Italia": "Coppa Italia",
    "Cristal Palace": "Crystal Palace",
    "Cristiano": "Cristiano Ronaldo",
    "Cristiano Ronaldo": "Cristiano Ronaldo",
    "Crystal Palace": "Crystal Palace",
    "Csiky Begirishtijn": "Txiki Begiristain",
    "Cuncu": "Christopher Nkunku",
    "Cunha": "Cunha",
    "D'Onarumma": "Donnarumma",
    "D'Unfries": "Denzel Dumfries",
    "Dani Carvajal": "Dani Carvajal",
    "Dani Ceballos": "Dani Ceballos",
    "Dani Olmo": "Dani Olmo",
    "Daniel Olmo": "Dani Olmo",
    "Danielmo": "Dani Olmo",
})
corrections.update({
    "Daniolmo": "Dani Olmo",
    "Danny Carvajal": "Dani Carvajal",
    "Dario Esucco": "Dario Essugo",
    "Dario Esugo": "Dario Essugo",
    "Darwin Nunes": "Darwin Núñez",
    "Darwin Unets": "Darwin Núñez",
    "Darwin-Uniats": "Darwin Núñez",
    "Darwinuñez": "Darwin Núñez",
    "Datrofofana": "Djaté Fofana",
    "Davi D'Angico": "David D'Angelo",
    "Davide Fratesi": "David Fratesi",
    "Davide Gea": "David De Gea",
    "Davies": "Alphonso Davies",
    "De Bruyne": "Kevin De Bruyne",
    "De Zerbi": "Roberto De Zerbi",
    "DeLigt": "Matthijs de Ligt",
    "DePie": "Donyell Malen",
    "Dean Hoisen": "Dean Henderson",
    "Dean Hoyes": "Dean Henderson",
    "Dean Hoys": "Dean Henderson",
    "Dean Hoysen": "Dean Henderson",
    "Dean Hoyson": "Dean Henderson",
    "Dean Huizen": "Dean Henderson",
    "Deco": "Deco",
    "Delap": "Peter Crouch",  # or "Delap" (Peter Crouch and Rory Delap are different)
    "Dele Alli": "Dele Alli",
    "Delic": "Delic",
    "Delict": "De Ligt",
    "Delight": "De Ligt",
    "Delop": "Delap",
    "Dembélé": "Ousmane Dembélé",
    "Den Hoysen": "Dean Henderson",
    "Deschamps": "Didier Deschamps",
    "Desi Redway": "Desiree Redway",
    "Desiree Dway": "Desiree Redway",
    "Desiree Dwaye": "Desiree Redway",
    "Desiree Dwe": "Desiree Redway",
    "Desiree Dwey": "Desiree Redway",
    "Di Bala": "Ángel Di María",
    "Di Bò": "Ángel Di María",
    "Di Marco": "Federico Di Marco",
    "DiSasi": "Axel Disasi",
    "Diallo": "Amad Diallo",
    "Diatz": "Diatz",
    "Didier Deschamps": "Didier Deschamps",
    "Diego Leon": "Diego León",
    "Diego León": "Diego León",
    "Dijk": "Virgil van Dijk",
    "Dion": "Dion",
    "Disasi": "Axel Disasi",
    "Disazí": "Axel Disasi",
    "Dizazí": "Axel Disasi",
    "Dobbic": "Dobbic",
    "Dominic Solanke": "Dominic Solanke",
    "Domino": "Dominic",
    "Don": "Don",
    "Doni Rahola": "Doni Rahola",
    "Donnarum": "Donnarumma",
    "Dorco": "Dorco",
    "Dorcou": "Dorco",
    "Dorgo": "Dorgo",
    "Dorgu": "Dorgo",
    "Dortmund": "Borussia Dortmund",
    "Dothbik": "Dothbik",
    "Douglas Lewis": "Douglas Luiz",
    "Dovan": "Dovan",
    "Dugarte": "Dugarte",
    "Dujan Blavich": "Dušan Blavčić",
    "Durant": "Kevin Durant",
    "Dusan Blauvić": "Dušan Blavčić",
    "EZ": "EZ",
    "Eberheciez": "Eberheciez",
    "Ed": "Ed",
    "Edd interstich": "Eddie Interstich",
    "Edding Ketya": "Eddie Ketya",
    "Eder Militao": "Éder Militão",
    "Ederson": "Ederson",
    "Edu": "Edu",
    "Edu Gaspar": "Edu Gaspar",
    "Edze": "Edze",
    "Eepswich Town": "Ipswich Town",
    "Eidhen Hirn": "Eidhen Hirn",
    "Eintracht Frankfurt": "Eintracht Frankfurt",
    "Elise": "Elise",
    "Emery": "Unai Emery",
    "Emile Smithrow": "Emile Smith Rowe",
    "Empoli": "Empoli",
    "England": "England",
    "Enso Mareska": "Enzo Maresca",
    "Enso Mariska": "Enzo Maresca",
    "Enzo Canna Bigic": "Enzo Cannavacciuolo",
    "Enzo Mareiska": "Enzo Maresca",
    "Enzo Mareska": "Enzo Maresca",
    "Enzo Marezca": "Enzo Maresca",
    "Enzo Mariesca": "Enzo Maresca",
    "Enzo Mariscal": "Enzo Maresca",
    "Enzo Mariska": "Enzo Maresca",
    "Enzo Marésca": "Enzo Maresca",
    "Ep Guardiola": "Pep Guardiola",
    "Eric": "Eric",
    "Eric Dyer": "Eric Dyer",
    "Eric Kane": "Eric Kane",
    "Eric Tenarch": "Erik Ten Hag",
    "Eric Tenhag": "Erik Ten Hag",
    "Eric Tenhug": "Erik Ten Hag",
    "Erick Garcia": "Eric Garcia",
    "Ericsson": "Ericsson",
    "Eriken Haag": "Erik ten Hag",
    "Eriken Hague": "Erik ten Hag",
    "Eriksen": "Christian Eriksen",
    "Eriton Hague": "Erik ten Hag",
    "Eriton Hugg": "Erik ten Hag",
    "Eritre": "Eritrea",
    "Erling Haaland": "Erling Haaland",
    "Espanyol": "Espanyol",
    "Esugo": "Dario Essugo",
    "Etan Waneri": "Ethan Waneri",
    "Ethan Juaneri": "Ethan Waneri",
    "Ethan Waneri": "Ethan Waneri",
    "Eton hug": "Ethan Waneri",
    "Europa League": "UEFA Europa League",
    "Euros": "UEFA European Championship",
    "Evan Ilson": "Evan Ilson",
    "Everton": "Everton",
    "Eze": "Eberechi Eze",
    "FA": "FA Cup",
    "Fab": "Fab",
    "Fabio Carvalho": "Fabio Carvalho",
    "Fabio Vieira": "Fábio Vieira",
    "Fabri": "Fabri",
    "Fabriz Cermano": "Fabrizio Romano",
    "Fabriz Fermanoguire": "Fabrizio Romano",
    "Fabrizio": "Fabrizio Romano",
    "Fabrizio Romano": "Fabrizio Romano",
    "Fabrizio Romano 3": "Fabrizio Romano",
    "Faier": "Faier",
    "Fajé": "Faier",
    "Fali Ramadani": "Fali Ramadani",
    "Fana": "Fana",
    "Federation": "Football Federation",
    "Federico Chiesa": "Federico Chiesa",
    "Federico Di Marco": "Federico Di Marco",
    "Federico Kiesi": "Federico Chiesa",
    "Felix": "João Félix",
    "Fenerbahce": "Fenerbahçe",
    "Fenerebacce": "Fenerbahçe",
    "Fenerebaccio": "Fenerbahçe",
})
corrections.update({
    "Ferdi Cadioglu": "Ferdi Kadıoğlu",
    "Ferguson": "Sir Alex Ferguson",
    "Ferland": "Ferland Mendy",
    "Ferland Mende": "Ferland Mendy",
    "Ferland Mendy": "Ferland Mendy",
    "Fermin": "Fermín López",
    "Fermin López": "Fermín López",
    "Ferran Soriano": "Ferran Soriano",
    "Feyenoord": "Feyenoord",
    "Feynord": "Feyenoord",
    "Filipp Jorgensen": "Filip Jørgensen",
    "Fiorentina": "Fiorentina",
    "Flamengo": "Flamengo",
    "Flick": "Hansi Flick",
    "Florentino": "Florentino Pérez",
    "Florentino Peretz": "Florentino Pérez",
    "Florentino Perez": "Florentino Pérez",
    "Florian Timo Peretz": "Florentino Pérez",
    "Florian Veers": "Florian Wirtz",
    "Florian Vierce": "Florian Wirtz",
    "Florian Virts": "Florian Wirtz",
    "Florian Weirce": "Florian Wirtz",
    "Florian Wirth": "Florian Wirtz",
    "Floriano Perez": "Florentino Pérez",
    "Fofana": "Mady Camara",
    "Football": "Football",
    "Forest": "Nottingham Forest",
    "Forest News": "Nottingham Forest",
    "Francisco Concesao": "Francisco Conceição",
    "Francisco Conceysau": "Francisco Conceição",
    "Franco Mastantuano": "Franco Mastantuano",
    "Frank": "Frank Lampard",
    "Frankie": "Frankie de Jong",
    "Frankie De Jong": "Frenkie de Jong",
    "Fratesi": "David Fratesi",
    "Frimpong": "Jeremie Frimpong",
    "Fulcruc": "Fulcrum",
    "Fulham": "Fulham",
    "Full Crew": "Full Crew",
    "Furlani": "Furlani",
    "Gabriel": "Gabriel",
    "Gabriel Mac": "Gabriel Magalhães",
    "Gabriel Mack": "Gabriel Magalhães",
    "Gabriel Mecc": "Gabriel Magalhães",
    "Gala": "Galatasaray",
    "Galatasaray": "Galatasaray",
    "Galaxy": "LA Galaxy",
    "Galeno": "Galeno",
    "Gallagher": "Conor Gallagher",
    "Garatasaray": "Galatasaray",
    "Garcia": "Eric García",
    "Garnaccio": "Nicolás Garnaccio",
    "Garte": "Garte",
    "Gata Salai": "Gata Salai",
    "Gata Sarai": "Gata Salai",
    "Gavi": "Gavi",
    "Gehi": "Gehi",
    "General Transfer": "General Transfer",
    "Genoa": "Genoa",
    "Geofelix": "Geofelix",
    "George Mandes": "Jorge Mendes",
    "George Mendes": "Jorge Mendes",
    "George Mendez": "Jorge Mendes",
    "Gerard Martín": "Gerard Moreno",
    "Germain": "Moussa Dembélé",
    "Gero": "Gero",
    "Gertrude": "Gertrude",
    "Ghidorodriguez": "Ghidorodriguez",
    "Giantes": "Giantes",
    "Gibbs White": "Morgan Gibbs-White",
    "Gigi D'Onarumma": "Gianluigi Donnarumma",
    "Gilmour": "Billy Gilmour",
    "Gio Cancelo": "João Cancelo",
    "Giocares": "Giocares",
    "Giochres": "Giocares",
    "Giorginho": "Jorginho",
    "Giorgio Cancelo": "João Cancelo",
    "Giorgio Hato": "Giorgio Hatto",
    "Giorgio Hattu": "Giorgio Hatto",
    "Gioro": "Giorgio",
    "Giovanni Canda": "Giovanni Canda",
    "Giovanni Kenda": "Giovanni Kenda",
    "Giovanni LoCelso": "Giovani Lo Celso",
    "Giovanni Manna": "Giovanni Manna",
    "Girona": "Girona",
    "Giuntoli": "Fabrizio Giuntoli",
    "Gjoklis": "Gjoklis",
    "Gjokores": "Gjokores",
    "Gjokoress": "Gjokores",
    "Glason Bremerne": "Glasán Bremer",
    "Golo Cante": "N'Golo Kanté",
    "Gomes": "Ruben Gomes",
    "Goncalo Ramos": "Gonçalo Ramos",
    "Gonzalo Ramos": "Gonçalo Ramos",
    "Goretzka": "Leon Goretzka",
    "Graham Potter": "Graham Potter",
    "Grahamio": "Graham Potter",
    "Greenwood": "Mason Greenwood",
    "Gremio": "Grêmio",
    "Griezmann": "Antoine Griezmann",
    "Grigno": "Grigno",
    "Grimaldo": "Álex Grimaldo",
    "Grêmio": "Grêmio",
    "Guardiola": "Pep Guardiola",
    "Guido Rodríguez": "Guido Rodríguez",
    "Gundo": "Ilkay Gündogan",
    "Gundogan": "Ilkay Gündogan",
    "Gustepe": "Gustavo",
    "Gutiérrez": "Gutiérrez",
    "Haag": "Haag",
    "Haaland": "Erling Haaland",
    "Hague": "Hague",
    "Harry Kane": "Harry Kane",
    "Harry Maguire": "Harry Maguire",
    "Hattu": "Hattu",
    "Haven": "Haven",
    "Helmhildreed": "Helmhildreed",
    "Hendrik": "Hendrik",
    "Hermoso": "Jorge Meré Hermoso",
    "Heven": "Heven",
    "Hoiberg": "Fredrik Hoiberg",
    "Hoiland": "Hoiland",
    "Hoisen": "Dean Henderson",
    "Hoyes": "Dean Henderson",
    "Hoys": "Dean Henderson",
})
corrections.update({
    "Hoysen": "Dean Henderson",
    "Hoyson": "Dean Henderson",
    "Hugo Viana": "Hugo Viana",
    "Hulé Lopetegui": "Julen Lopetegui",
    "Hummels": "Mats Hummels",
    "Humphill": "Humphreys",
    "INEOS": "INEOS",
    "Ibera": "Ibrahima Konaté",
    "Ibera Konate": "Ibrahima Konaté",
    "Ibrahim Conmate": "Ibrahima Konaté",
    "Ibrahima Conate": "Ibrahima Konaté",
    "Ibrahima Konate": "Ibrahima Konaté",
    "Ibu Konate": "Ibrahima Konaté",
    "Ilhae Gundogan": "Ilkay Gündogan",
    "Imenets": "Imen Es",
    "Important": "Important",
    "Ine": "INEOS",
    "Ineos": "INEOS",
    "Inigo": "Iñigo Martínez",
    "Insaghi": "Filippo Inzaghi",
    "Insagi": "Filippo Inzaghi",
    "Inter": "Inter Milan",
    "Inter Miami": "Inter Miami",
    "Interact": "Interact",
    "Ipswich": "Ipswich Town",
    "Ipswich Town": "Ipswich Town",
    "Iquipeña": "Iquipeña",
    "Iralo": "Iralo",
    "Isaac": "Isaac",
    "Ismael Ben-Nacer": "Ismaël Bennacer",
    "Ito": "Ito",
    "Ivan Tony": "Ivan Tony",
    "Ivatuni": "Ivatuni",
    "Jack Greenish": "Jack Grealish",
    "Jadall Sancho": "Jadon Sancho",
    "Jadon": "Jadon Sancho",
    "Jadon Sancho": "Jadon Sancho",
    "Jadon Sancio": "Jadon Sancho",
    "Jalver Cusen": "Javier Cusen",
    "Jamal Musialla": "Jamal Musiala",
    "Jamie Byneghitten": "Jamie Vardy",
    "Jamie Vardy": "Jamie Vardy",
    "Jan Kouto": "Jan Kouto",
    "Jared Brantwhite": "Jared Branthwaite",
    "Jarek Kansa": "Jarek Kansa",
    "Jason Wilcox": "Jason Wilcox",
    "Jauneves": "João Neves",
    "Javi Guerra": "Javi Guerra",
    "Jaydon Sanchez": "Jadon Sancho",
    "Jean-Eves": "Jean-Eudes",
    "Jean-Huez": "Jean-Hugues",
    "Jeremy Frimpong": "Jeremie Frimpong",
    "Jermaine": "Jermaine",
    "Jimenez": "Raúl Jiménez",
    "Jo Felix": "João Félix",
    "Joan Garcia": "Joan García",
    "Joao": "João",
    "Joao Felix": "João Félix",
    "Joao Neves": "João Neves",
    "Joao Nevesh": "João Neves",
    "Joe": "Joe",
    "Joe Bellingham": "Jude Bellingham",
    "Joe Felix": "João Félix",
    "Joe Felix Gallagher": "João Félix / Conor Gallagher",
    "Joe Gomez": "Joe Gomez",
    "Jofelic": "João Félix",
    "John Durand": "John Durand",
    "John Durant": "John Durand",
    "John Durán": "John Durand",
    "John Eves": "John Eves",
    "John Nicardoso": "John Nicardoso",
    "Johnny Evans": "Jonny Evans",
    "Jonathan": "Jonathan",
    "Jonathan David": "Jonathan David",
    "Jonathan Ta": "Jonathan Tah",
    "Jonathan Taa": "Jonathan Tah",
    "Jonathan Tah": "Jonathan Tah",
    "Jonathan Tato": "Jonathan Tah",
    "Jonathan Tau": "Jonathan Tah",
    "Jonathan Tà": "Jonathan Tah",
    "Jorgens": "Jørgensen",
    "Jorgensen": "Jørgensen",
    "Jorot": "Jørgensen",
    "Jose Mourinho": "José Mourinho",
    "Jose Murinho": "José Mourinho",
    "Josh Achenpong": "Jeremie Frimpong",
    "Joshua": "Joshua",
    "Joshua Azierze": "Joshua Zirkzee",
    "Joshua Kimmich": "Joshua Kimmich",
    "Joshua Zierze": "Joshua Zirkzee",
    "Joshua Zilder": "Joshua Zirkzee",
    "Joshua Zirce": "Joshua Zirkzee",
    "Jowicz": "Jowicz",
    "João": "João",
    "João Cancelo": "João Cancelo",
    "João Felix": "João Félix",
    "João Neves": "João Neves",
    "João Nevesh": "João Neves",
    "Jr": "Jr",
    "Juan Bissac": "Juan Bissa",
    "Juan Garcia": "Juan García",
    "Juan Martinez": "Juan Martínez",
    "Juaneri": "Juaneri",
    "Jude": "Jude Bellingham",
    "Juli Alvarez": "Julián Álvarez",
    "Juli Álvarez": "Julián Álvarez",
    "Julian": "Julián Álvarez",
    "Julian Alvarez": "Julián Álvarez",
    "Julio": "Julio",
    "Julio Nalvarez": "Julián Álvarez",
    "Juma Bah": "Juma Bah",
    "Junior Pedroso": "Junior Pedroso",
    "Jurgen Klopp": "Jürgen Klopp",
    "Juve": "Juventus",
    "Juvent": "Juventus",
    "Juventus": "Juventus",
    "Jürgen Klopp": "Jürgen Klopp",
    "KEPA": "Kepa Arrizabalaga",
    "Kai": "Kai",
    "Kai Walker": "Kyle Walker",
    "Kailor Navas": "Keylor Navas",
    "Kamara": "Kamara",
    "Kangin Lee": "Kang-in Lee",
    "Kanjin Lee": "Kang-in Lee",
    "Kansa": "Kansa",
    "Kara Fiori": "Kara Fiori",
    "Karim Adeyemi": "Karim Adeyemi",
    "Karni": "Karni",
    "Karny": "Karni",
    "Karny Chukwameka": "Karny Chukwuemeka",
    "Katia": "Katia",
    "Kazemiro": "Casemiro",
    "Kelly": "Kelly",
    "Ken": "Ken",
    "Kenda": "Kenda",
    "Kepa": "Kepa Arrizabalaga",
    "Keppa": "Kepa Arrizabalaga",
    "Kerkac": "Kerkac",
    "Kerkens": "Kerkens",
    "Ketia": "Ketia",
    "Ketya": "Ketya",
    "Kevin": "Kevin",
    "Kevin Danso": "Kevin Danso",
    "Kevin De Bruijn": "Kevin De Bruyne",
    "Kevin De Bruyne": "Kevin De Bruyne",
    "Kevin de Bruyne": "Kevin De Bruyne",
    "Kiesa": "Kiesza",
    "Kiesa Liverpool": "Kiesza",
    "Kiesi": "Kiesza",
    "Kim": "Kim",
    "Kim Min Jae": "Kim Min-jae",
    "Kimmich": "Joshua Kimmich",
    "Kinej": "Kane",
    "Kingsley": "Kingsley",
    "Kingsley Coman": "Kingsley Coman",
    "Kingsley Common": "Kingsley Coman",
    "Kinsley Common": "Kingsley Coman",
    "Kipra": "Kipra",
    "Klopp": "Jürgen Klopp",
    "Kobe": "Kobe",
    "Kobe Maino": "Kobe",
    "Kobe Mainu": "Kobe",
    "Kobe Meno": "Kobe",
    "Kolomoni": "Kolomoni",
    "Komod": "Komod",
    "Konate": "Ibrahima Konaté",
    "Ku": "Ku",
    "Kubo": "Takefusa Kubo",
    "Kugia": "Kugia",
    "Kuiper": "Kuiper",
    "Kuku": "Kuku",
    "Kuncu": "Kuncu",
    "Kung": "Kung",
    "Kung-Ku": "Kung-Ku",
    "Kungku": "Kungku",
    "Kunko": "Kunko",
    "Kunkou": "Kunkou",
    "Kunku": "Christopher Nkunku",
    "Kurtua": "Thibaut Courtois",
    "Kuzanov": "Kuzanov",
    "Kvarashkelia": "Khvicha Kvaratskhelia",
    "Kvarschkelia": "Khvicha Kvaratskhelia",
    "Kyla": "Kyla",
    "Kyle Walker": "Kyle Walker",
    "L'Ala Clé": "L'Alcala",
    "L'Arabie": "L'Arabie",
    "LA Galaxy": "LA Galaxy",
    "LAFC": "LAFC",
    "La Liga": "La Liga",
    "La Migliamal": "La Migliamal",
})
corrections.update({
    "La Milla Mal": "La Masia",
    "La Mini Fati": "Ansu Fati",
    "La Porta": "La Porta",
    "La Sociedad": "Real Sociedad",
    "Lans": "Lens",
    "Lanz": "Lanz",
    "Laurenti": "Laurenti",
    "Lautaro Martinez": "Lautaro Martínez",
    "Lazio": "Lazio",
    "Le Vercusion": "Leverkusen",
    "Le Verkuzen": "Leverkusen",
    "League": "League",
    "Leal": "Leal",
    "Leao": "Rafael Leão",
    "Lecce": "Lecce",
    "Left": "Left",
    "Leicester": "Leicester City",
    "Leicester City": "Leicester City",
    "Leipzig": "RB Leipzig",
    "Lenglet": "Clément Lenglet",
    "Leni Gero": "Lenny Jorot",
    "Leni Gioro": "Lenny Jorot",
    "Lenny Gero": "Lenny Jorot",
    "Lenny Gioro": "Lenny Jorot",
    "Lenny Jorot": "Lenny Jorot",
    "Lenny Jorow": "Lenny Jorot",
    "Lens": "Lens",
    "Lenz": "Lenz",
    "Leon Bailey": "Leon Bailey",
    "Let": "Let",
    "Levercusan": "Leverkusen",
    "Leverkusen": "Leverkusen",
    "Lewandowski": "Robert Lewandowski",
    "Lewis Kelly": "Lewis Kelly",
    "Liberals": "Liberals",
    "Liga": "La Liga",
    "Light Sig": "Light Sig",
    "Ligue 1": "Ligue 1",
    "Lille": "Lille",
    "Lindelof": "Victor Lindelöf",
    "Lindstrom": "Lindstrom",
    "Lino Soloku": "Lino Soloku",
    "Liverpool": "Liverpool",
    "Liverpool Juventus": "Liverpool vs Juventus",
    "Liverpool Valencia": "Liverpool vs Valencia",
    "Llan Uro": "Llan Uro",
    "LoCelso": "Giovani Lo Celso",
    "Lobotka": "Stanislav Lobotka",
    "Lorenzo": "Lorenzo",
    "Lorenzo Luca": "Lorenzo Luca",
    "Louis Campos": "Luis Campos",
    "Louis Serrique": "Luis Serrique",
    "Luca": "Luca",
    "Luca Gurnaduat": "Luca Marianucci",
    "Luca Jowicz": "Luca Jowicz",
    "Luca Marianucci": "Luca Marianucci",
    "Luca Modric": "Luka Modrić",
    "Lucas Vazquez": "Lucas Vázquez",
    "Lucerna": "Lucerna",
    "Lucho": "Lucho",
    "Lucqueba": "Lucas Quezada",
    "Lugarte": "Manuel Lugarte",
    "Luis": "Luis",
    "Luis Diaz": "Luis Díaz",
    "Luis Díaz": "Luis Díaz",
    "Luis Enrique": "Luis Enrique",
    "Luis Kelly": "Luis Kelly",
    "Lukaku": "Romelu Lukaku",
    "Lukman": "Lukman",
    "Lulia": "Lulia",
    "Lunin": "Andriy Lunin",
    "Lyam Delap": "Lyam Delap",
    "Lyon": "Lyon",
    "Lyon Bailey": "Leon Bailey",
    "Lyon Bayley": "Leon Bailey",
    "MLS": "MLS",
    "MacTomine": "Macdomine",
    "MacTone": "Macdomine",
    "Macdominane": "Macdomine",
    "Macdomine": "Macdomine",
    "Madrid": "Real Madrid",
    "Maduakio": "Maduakio",
    "Maduweke": "Maduakio",
    "Maguire": "Harry Maguire",
    "Maison Greenwood": "Mason Greenwood",
    "Maison Mount": "Mason Mount",
    "Majority": "Majority",
    "Majority United": "Manchester United",
    "Malachli": "Malacia",
    "Malacia": "Tyrell Malacia",
    "Malasia": "Malaysia",
    "Malen": "Donyell Malen",
    "Malik Chao": "Malik Chao",
    "Malik Ciaoh": "Malik Chao",
    "Malin": "Malin",
    "Mamadou Sarre": "Mamadou Sakho",
    "Mamar Daszvili": "Mamardashvili",
    "Mamardash Vili": "Mamardashvili",
    "Mamardashvili": "Anzor Mamardashvili",
    "Man City": "Manchester City",
    "Man United": "Manchester United",
    "Manchester": "Manchester",
    "Manchester City": "Manchester City",
    "Manchester United": "Manchester United",
    "Maneri": "Maneri",
    "Manu": "Manu",
    "Manu Cone": "Manu Ugarte",
    "Manu Garte": "Manu Ugarte",
    "Manu Ugart": "Manu Ugarte",
    "Manu Ugarte": "Manu Ugarte",
    "Manuel Hougarte": "Manu Ugarte",
    "Manuel Lugarte": "Manuel Lugarte",
    "Manuel Ugarte": "Manu Ugarte",
    "Manuel Ugarthe": "Manu Ugarte",
    "Marc": "Marc",
    "Marc Gehe": "Marc",
    "Marc Gehi": "Marc",
    "Marc Gehilding": "Marc",
    "Marc Guillaud": "Marc",
    "Marcel": "Marcel",
    "Marcelo": "Marcelo",
    "Marco": "Marco",
    "Marco Asensio": "Marco Asensio",
    "Marco Royce": "Marco Royce",
    "Marco Silva": "Marco Silva",
    "Marcos Rashford": "Marcus Rashford",
    "Marcos Rushford": "Marcus Rashford",
    "Marcus Rashford": "Marcus Rashford",
    "Marcus Rush": "Marcus Rashford",
    "Marcus Rushford": "Marcus Rashford",
    "Mardas Vili": "Mamardashvili",
    "Mardaschmiedi": "Mardaschmiedi",
    "Marejka": "Marejka",
    "Maresca": "Maresca",
    "Mareska": "Maresca",
    "Marezca": "Maresca",
    "Margehi": "Margehi",
    "Marguerite": "Marguerite",
    "Marguerjee": "Marguerjee",
    "Maria Nucci": "Maria Nucci",
    "Marianucci": "Luca Marianucci",
    "Marinakis": "Evangelos Marinakis",
    "Mario Balotelli": "Mario Balotelli",
    "Mario Hermoso": "Mario Hermoso",
    "Mariska": "Mariska",
    "Marmous": "Marmoush",
    "Marmoush": "Karim Adeyemi",
    "Marsale": "Marsale",
    "Marseille": "Marseille",
    "Martin": "Martin",
    "Martin Subimendi": "Martin Zubimendi",
    "Martin Zubimendi": "Martin Zubimendi",
    "Martinelli": "Gabriel Martinelli",
    "Martín Subimendi": "Martin Zubimendi",
    "Martín Zubimendi": "Martin Zubimendi",
    "Masarawi": "Masarawi",
    "Maseraui": "Masarawi",
    "Mason Greenwood": "Mason Greenwood",
    "Masrawi": "Masarawi",
    "Massimiliano Allegri": "Massimiliano Allegri",
    "Massimiliano Legri": "Massimiliano Allegri",
    "Mastantuano": "Mastantuano",
    "Matai": "Matai",
    "Matais Delict": "Matías Deligt",
    "Mateus Cugna": "Mateusz Cunha",
    "Mateus Cunha": "Mateusz Cunha",
    "Mateusz": "Mateusz",
    "Mateusz Cunha": "Mateusz Cunha",
    "Mateusz Kugia": "Mateusz Cunha",
    "Mathias Suley": "Matthias Suley",
    "Mati": "Mati",
    "Mati Stel": "Matías Stell",
    "Mati Stell": "Matías Stell",
    "Matias": "Matías",
    "Matias Delict": "Matías Deligt",
    "Matias Deligth": "Matías Deligt",
    "Matias delict": "Matías Deligt",
    "Matias deligt": "Matías Deligt",
    "Matis Tell": "Matías Tell",
    "Matissa Mugu": "Matissa Mugu",
    "Matisse": "Matisse",
    "Matisse Amugu": "Matisse",
    "Matisse Tell": "Matías Tell",
    "Matize Delict": "Matías Deligt",
    "Mats Hummels": "Mats Hummels",
    "Matsumelze": "Mats Hummels",
    "Matt Estelle": "Matt Estelle",
    "Matt Ice Delict": "Matías Deligt",
    "Matte": "Matteo",
    "Matteo": "Matteo",
    "Matteo Schcugna": "Matteo Scugna",
    "Matteo Scugna": "Matteo Scugna",
    "Matteo Skuña": "Matteo Scugna",
    "Matthias Delict": "Matías Deligt",
    "Matthias Delight": "Matías Deligt",
    "Matti Stelto": "Matías Stell",
    "Mattias Suley": "Matthias Suley",
    "Mattie Stell": "Matías Stell",
    "Mattis Tell": "Matías Tell",
    "Mattisthel": "Matías Tell",
    "Mauricio Pochettino": "Mauricio Pochettino",
    "Mauricio Posciettino": "Mauricio Pochettino",
    "Maurizio Pocettino": "Mauricio Pochettino",
    "Max": "Max",
    "Max Allegri": "Massimiliano Allegri",
    "Max Eberl": "Max Eberl",
    "May United": "Manchester United",
    "Mayonetta": "Mayonetta",
    "Mazraoui": "Noussair Mazraoui",
    "Mazrawi": "Noussair Mazraoui",
    "McKenney": "McKenney",
    "Mectomin": "Mectomin",
    "Medina": "Medina",
    "Memphis De Pie": "Memphis Depay",
    "Memphis DePie": "Memphis Depay",
    "Mendez": "Mendez",
    "Mendez City": "Mendez City",
    "Mengian": "Mengian",
    "Meret": "Alex Meret",
    "Merino": "Mikel Merino",
    "Micah Fajé": "Micah Faye",
    "Michaelo Moudric": "Mihailo Moudric",
    "Michel Arteta": "Mikel Arteta",
    "Michel Artheta": "Mikel Arteta",
    "Michel Merino": "Mikel Merino",
    "Mifica": "Mifica",
    "Miguel Gutiérrez": "Miguel Gutiérrez",
    "Mihailo Moudric": "Mihailo Moudric",
    "Mika Faier": "Micah Faye",
    "Mikau Tadze": "Mikau Tadze",
    "Mike Panders": "Mike Panders",
    "Mila Skriniar": "Milan Škriniar",
    "Milan": "AC Milan",
    "Milan-Berteneiro": "Milan",
    "Militao": "Éder Militão",
    "Milo Scherke": "Milo Scherke",
    "Miloš Kerkens": "Miloš Kerkens",
    "Miquel Artheta": "Mikel Arteta",
    "Miquel Merino": "Mikel Merino",
    "Miquela Artheta": "Mikel Arteta",
    "Mitoma": "Kaoru Mitoma",
    "Mo": "Mohamed Salah",
    "Mo Salah": "Mohamed Salah",
    "Mo Simacan": "Mohamed Salah",
    "Modric": "Luka Modrić",
    "Moise Ken": "Moise Kean",
    "Monaco": "AS Monaco",
    "Monodion": "Monodion",
    "Monsala": "Monsala",
    "Monschi": "Monschi",
    "Monza": "AC Monza",
    "Moradion": "Moradion",
    "Morata": "Álvaro Morata",
    "Morgan Gibbs White": "Morgan Gibbs-White",
    "Morodion": "Moradion",
    "Mosala": "Mohamed Salah",
    "Mosalab": "Mohamed Salah",
    "Motta": "Motta",
    "Moucoco": "Arnaud Moukoko",
    "Moudric": "Mihailo Moudric",
    "Moukoko": "Arnaud Moukoko",
    "Mount": "Mason Mount",
    "Mousiala": "Jamal Musiala",
    "Moussala": "Jamal Musiala",
    "Mukoko": "Arnaud Moukoko",
    "Musialla": "Jamal Musiala",
    "Muzzo": "Muzzo",
    "NAMAR JUNIOR": "Namar Junior",
    "Nacho": "Nacho Fernández",
    "Naples": "Napoli",
    "Napoli": "Napoli",
    "Napoli PSG": "Napoli vs PSG",
    "Narguinuñez": "Narguinuñez",
    "Naser": "Naser",
    "Nata": "Nata",
    "Natan": "Natan",
    "Nausie Man": "Nausie Man",
    "Nene Durgeles": "Nene Durgeles",
    "Neres": "David Neres",
    "Neshworth": "Neshworth",
    "Neto": "Neto",
    "Neum": "Neum",
    "Newcastle": "Newcastle United",
    "Neymar": "Neymar Jr.",
    "Neymar Jr": "Neymar Jr.",
    "Nice": "OGC Nice",
    "Nico": "Nico",
    "Nico Gonzalez": "Nico González",
    "Nico Jackson": "Nico Jackson",
    "Nico O'Reilly": "Nico O'Reilly",
    "Nico Paz": "Nico Paz",
    "Nico Reilly": "Nico Reilly",
    "Nico Riley": "Nico Riley",
    "Nico Williams": "Nico Williams",
    "Nico pass": "Nico Pass",
})
corrections.update({
    "Nicoh": "Nico",
    "Nicohilliams": "Nico Williams",
    "Nicolò Teta": "Nicolò Teta",
    "Nicopas": "Nico Paz",
    "Nicopats": "Nico Paz",
    "Nicopaz": "Nico Paz",
    "Niko": "Niko",
    "Niko Williams": "Nico Williams",
    "Nikon": "Niko",
    "Nipan": "Nipan",
    "Noisen": "Noisen",
    "Noni": "Noni",
    "Noni Maduweke": "Noni Maduweke",
    "Nothing Unforest": "Nottingham Forest",
    "Nottingham Forest": "Nottingham Forest",
    "Nudou Mendes": "Nuno Mendes",
    "Nuggets": "Nuggets",
    "Nugolkeeper": "Goalkeeper",
    "Nuno": "Nuno",
    "Nuno Mendes": "Nuno Mendes",
    "Nuno Tavares": "Nuno Tavares",
    "Nusa": "Nusa",
    "Nusair Mazraoui": "Noussair Mazraoui",
    "Nusair Mazrawi": "Noussair Mazraoui",
    "Núñez": "Darwin Núñez",
    "O'Realy": "O'Reilly",
    "OSM": "OSM",
    "Obameyang": "Pierre-Emerick Aubameyang",
    "Oka": "Oka",
    "Okafour": "Okafor",
    "Ole Gunnar Solskjaer": "Ole Gunnar Solskjaer",
    "Oli Watkins": "Ollie Watkins",
    "Olise": "Michael Olise",
    "Olmo": "Dani Olmo",
    "Olympiacos": "Olympiacos",
    "Olympic": "Olympique",
    "Olympic Lyon": "Olympique Lyon",
    "Olympic Marcel": "Olympique Marseille",
    "Olympic Marsale": "Olympique Marseille",
    "Olympic Marseille": "Olympique Marseille",
    "Olympique Lyon": "Olympique Lyon",
    "Olympique Marseille": "Olympique Marseille",
    "Omar Berra": "Omar Berra",
    "Omar Marmoush": "Karim Adeyemi",
    "Omerodion": "Omerodion",
    "Ommorodion": "Omerodion",
    "Omorodion": "Omerodion",
    "Onana": "Andre Onana",
    "Onaná": "Andre Onana",
    "One Football": "OneFootball",
    "OneFootball": "OneFootball",
    "Onosimen": "Onosimen",
    "Option": "Option",
    "Ortega": "Ortega",
    "Oscar Bob": "Oscar Bob",
    "Osiman": "Onyeka Osimhen",
    "Osimem": "Onyeka Osimhen",
    "Ossiman": "Onyeka Osimhen",
    "Ossimen": "Onyeka Osimhen",
    "Osumen": "Onyeka Osimhen",
    "Oven": "Oven",
    "Oylund": "Oylund",
    "Ozi Men": "Onyeka Osimhen",
    "Oziman": "Onyeka Osimhen",
    "Ozimán": "Onyeka Osimhen",
    "Ozyman": "Onyeka Osimhen",
    "Ozymen": "Onyeka Osimhen",
    "Ozzyman": "Onyeka Osimhen",
    "PSG": "Paris Saint-Germain",
    "PSV": "PSV Eindhoven",
    "Pablo Torre": "Pablo Torre",
    "Pacho": "Pacho",
    "Paixao": "Paixão",
    "Palace": "Crystal Palace",
    "Palas": "Palas",
    "Palmeiras": "Palmeiras",
    "Panders": "Panders",
    "Panmecano": "Panmecano",
    "Pao Víctor": "Pao Víctor",
    "Paolo Fonseca": "Paulo Fonseca",
    "Paolo di Bala": "Paolo Di Bala",
    "Paris": "Paris Saint-Germain",
    "Paris Saint Jaman": "Paris Saint-Germain",
    "Paris Saint-Germain": "Paris Saint-Germain",
    "Paris Sancho": "Jadon Sancho",
    "Paris, San Germain": "Paris Saint-Germain",
    "Parma": "Parma",
    "Pascal Gross": "Pascal Groß",
    "Pat Guardiola": "Pep Guardiola",
    "Patino": "Patino",
    "Patric Dorgue": "Patrick Dorgu",
    "Patrick": "Patrick",
    "Patrick Dorco": "Patrick Dorgu",
    "Patrick Dorcou": "Patrick Dorgu",
    "Patrick Dorg": "Patrick Dorgu",
    "Patrick Dorgo": "Patrick Dorgu",
    "Patrick Dorgu": "Patrick Dorgu",
    "Patrick Dorgue": "Patrick Dorgu",
    "Paucu Barca": "Paucu Barca",
    "Paul Pogba": "Paul Pogba",
    "Paulo": "Paulo",
    "Paulo de Bala": "Paulo Di Bala",
    "Pedri": "Pedri",
    "Pedro": "Pedro",
    "Pedro Neto": "Pedro Neto",
    "Pedroneto": "Pedro Neto",
    "Pep": "Pep Guardiola",
    "Pep Guardiola": "Pep Guardiola",
    "Petrovic": "Petrović",
    "Philip Jorgensen": "Philip Jørgensen",
    "Philipp Jorgensen": "Philip Jørgensen",
    "Pierre Calulu": "Pierre Kalulu",
    "Pierre Obameyang": "Pierre-Emerick Aubameyang",
    "Piliqueta": "Piliqueta",
    "Pimenta": "Pimenta",
    "Pioli": "Stefano Pioli",
    "Playback": "Playback",
    "Pocettino": "Pochettino",
    "Pochettino": "Mauricio Pochettino",
    "Pogba": "Paul Pogba",
    "Pong": "Pong",
    "Porto": "FC Porto",
    "Posciettino": "Pochettino",
    "Poste Coglu": "Postecoglu",
    "Postecoglu": "Postecoglu",
    "Poubill": "Poubill",
    "Premier League": "Premier League",
    "Pro League": "Pro League",
    "Proton VPN": "ProtonVPN",
    "ProtonVPN": "ProtonVPN",
    "Quara": "Quara",
    "Quarascalia": "Quarascalia",
    "Quarascchelia": "Quarascalia",
    "Quaraschkeli": "Quarascalia",
    "Quichac Varascalia": "Quarascalia",
    "Quichacuara Scalia": "Quarascalia",
    "Qwarshkeli": "Quarascalia",
    "Rabiot": "Adrien Rabiot",
    "Rabiou": "Rabiot",
    "Rafa": "Rafa",
    "Rafa Ela Pimenta": "Rafa Pimenta",
    "Rafa Leal": "Rafa Leal",
    "Rafa Leao": "Rafael Leão",
    "Rafael Varan": "Raphaël Varane",
    "Rafaela Pimenta": "Rafa Pimenta",
    "Rafinha": "Rafinha",
    "Rahim Sterling": "Raheem Sterling",
    "Raijan Cherki": "Rayan Cherki",
    "Ram": "Ram",
    "Ram Steele": "Ram Steele",
    "Ram's Day": "Ram's Day",
    "Rami Abbas": "Rami Abbas",
    "Ramos": "Sergio Ramos",
    "Rams": "Rams",
    "Ramsdale": "Aaron Ramsdale",
    "Ramstein": "Ramstein",
})
corrections.update({
    "Randal": "Randal",
    "Raoucho": "Raucho",
    "Rashford": "Marcus Rashford",
    "Rasmus": "Rasmus",
    "Rasmus Hoiland": "Rasmus Hoiland",
    "Rasmus Oylund": "Rasmus Oylund",
    "Raucho": "Raucho",
    "Raul Asensio": "Raúl Asensio",
    "Raul Sociedad": "Real Sociedad",
    "Raul Sosietat": "Real Sociedad",
    "Ray Snelson": "Ray Snelson",
    "Rayados": "Monterrey Rayados",
    "Rayan Cherqui": "Rayan Cherki",
    "Raúl Asensio": "Raúl Asensio",
    "Real": "Real Madrid",
    "Real Betis": "Real Betis",
    "Real Leverkusen": "Bayer Leverkusen",
    "Real Madrid": "Real Madrid",
    "Real Sociedad": "Real Sociedad",
    "Rebulites": "Rebulites",
    "Red Bull": "Red Bull",
    "Red Bull Group": "Red Bull",
    "Red Bull Leipzig": "RB Leipzig",
    "Red Bull Light Sig": "RB Leipzig",
    "Red Bull Salzburg": "Red Bull Salzburg",
    "Reda Belayana": "Reda Belayana",
    "Redis": "Redis",
    "Regissoria": "Regissoria",
    "Reinder": "Reinders",
    "Reinders": "Reinders",
    "Ren": "Ren",
    "Renato Vega": "Renato Vega",
    "Revan Madrid": "Real Madrid",
    "Ricardo Calafioli": "Riccardo Calafiori",
    "Riccardo Calafiore": "Riccardo Calafiori",
    "Riccardo Calafiori": "Riccardo Calafiori",
    "Ricci": "Ricci",
    "Ricci Massara": "Riccò Massara",
    "Richard Dugues": "Richard Dukes",
    "Richard Dukes": "Richard Dukes",
    "Richard Hughes": "Richard Hughes",
    "Rick": "Rick",
    "Rio": "Rio",
    "Rio Gumo": "Rio Gumo",
    "Riz": "Riz",
    "Riz James": "Riz James",
    "Riz Nelson": "Riz Nelson",
    "Robert Lewandowski": "Robert Lewandowski",
    "Roberto De Zerbi": "Roberto De Zerbi",
    "Roberto Labbe": "Roberto Labbe",
    "Rodri": "Rodri",
    "Rodrigo": "Rodrigo",
    "Rodrigo Góez": "Rodrigo Góez",
    "Rodrigo Mora": "Rodrigo Mora",
    "Roma": "AS Roma",
    "Romelu": "Romelu Lukaku",
    "Romelu Lukaku": "Romelu Lukaku",
    "Romero Lukaku": "Romelu Lukaku",
    "Rommand": "Romelu Lukaku",
    "Ronald Araujo": "Ronald Araújo",
    "Ronald Raucho": "Raucho",
    "Ronaldo": "Cristiano Ronaldo",
    "Roni Araujo": "Ronald Araújo",
    "Ronny Araujo": "Ronald Araújo",
    "Rosenberg": "Rosenberg",
    "Rosiman": "Onyeka Osimhen",
    "Rosimand": "Onyeka Osimhen",
    "Rosimann": "Onyeka Osimhen",
    "Rosimen": "Onyeka Osimhen",
    "Rosimund": "Onyeka Osimhen",
    "Ruben": "Ruben",
    "Ruben Amarim": "Rúben Amorim",
    "Ruben Amorim": "Rúben Amorim",
    "Rud van Nesterloy": "Rud van Nistelrooy",
    "Rud van Nisterloy": "Rud van Nistelrooy",
    "Rudiger": "Antonio Rüdiger",
    "Rugarte": "Rugarte",
    "Ruinunias": "Ruinunias",
    "Rushford": "Marcus Rashford",
    "Ryan Cherokee": "Rayan Cherki",
    "Ryan Cherqui": "Rayan Cherki",
    "Saga": "Saga",
    "Saint-Germain": "Paris Saint-Germain",
    "Saka": "Bukayo Saka",
    "Sala": "Sala",
    "Salah": "Mohamed Salah",
    "Salaries": "Salaries",
    "Salemacers": "Salemacers",
    "Saliba": "William Saliba",
    "Salzburg": "Red Bull Salzburg",
    "Sam Omordion": "Sam Omorodion",
    "Samo Morodion": "Sam Omorodion",
    "Samo Ommoro Dion": "Sam Omorodion",
    "Samu Omerodion": "Sam Omorodion",
    "Samu Omorodion": "Sam Omorodion",
    "Samuel Dalle": "Samuel Dalle",
    "San Germain": "Paris Saint-Germain",
    "San Juan Moradion": "San Juan",
    "San Monodion": "San Juan",
    "Sanchez": "Alexis Sánchez",
    "Sancho": "Jadon Sancho",
    "Sancio": "Sancho",
    "Sander Berge": "Sander Berge",
    "Sanderland": "Sunderland",
    "Sandro Tonali": "Sandro Tonali",
    "Santa": "Santa",
    "Santa Becc": "Santa Becc",
    "Santa Bex": "Santa Becc",
    "Santi Jiménez": "Santi Jiménez",
    "Santiago": "Santiago",
    "Santiago Jimenez": "Santi Jiménez",
    "Santos": "Santos",
    "Saudi": "Saudi Arabia",
    "Saudi Pro League": "Saudi Pro League",
    "Savigno": "Savigno",
    "Savio": "Savio",
    "Schalobar": "Schalobar",
    "Schcugna": "Schcugna",
    "Schesco": "Schesco",
    "Schilwell": "Ben Chilwell",
    "Scott MacTone": "Scott MacTominay",
    "Scouse": "Scouse",
    "Scrinia": "Scrinia",
    "Scugna": "Scugna",
    "Sebastian Hönes": "Sebastian Hönes",
    "Selesao": "Selesao",
    "Sergei": "Sergei",
    "Sergei Bratcliffe": "Sergei Bratcliffe",
    "Sergei Muratcliffe": "Sergei Muratcliffe",
    "Sergi Ramos": "Sergio Ramos",
    "Sergim Ratcliffe": "Sergio Ramos",
    "Sergio": "Sergio",
    "Sergio Concey-Sao": "Sergio Conceição",
    "Sergio Ramos": "Sergio Ramos",
    "Sergio Roberto": "Sergio Roberto",
    "Serie A": "Serie A",
    "Serie B": "Serie B",
    "Serri Altemira": "Serri Altemira",
    "Serro Portegno": "Serro Portegno",
    "Sesco": "Sesco",
    "Sevilla": "Sevilla FC",
    "Seydon": "Seydou",
    "Seysao": "Seysao",
    "Shabbi Alonso": "Xabi Alonso",
    "Shabby Simons": "Xabi Alonso",
    "Shabi": "Xabi Alonso",
    "Shabi Alonso": "Xabi Alonso",
    "Shabia": "Xabi Alonso",
    "Shabia Alonso": "Xabi Alonso",
    "Shabia Lonso": "Xabi Alonso",
    "Shabia Lonsso": "Xabi Alonso",
    "Shabian Olso": "Xabi Alonso",
    "Shaby": "Xabi Alonso",
    "Shaby Alonso": "Xabi Alonso",
    "Shallow-Barre": "Shallow-Barre",
    "Shallow-Buy": "Shallow-Buy",
    "Shavi Simons": "Xavi Simons",
    "Silvanovos": "Silvanovos",
})
corrections.update({
    "Simacan": "Simakan",
    "Simeone": "Diego Simeone",
    "Similan": "Simakan",
    "Similand": "Simakan",
    "Simone Insaghi": "Simone Inzaghi",
    "Simone Insagi": "Simone Inzaghi",
    "Skriniar": "Milan Škriniar",
    "Skuña": "Škriniar",
    "Smith Rowe": "Emile Smith Rowe",
    "Smithrow": "Emile Smith Rowe",
    "So Alvarez": "S. Alvarez",
    "So Canna Bigic": "S. Canna Bigic",
    "Sociedad": "Real Sociedad",
    "Sofia": "Sofia",
    "Sofian Amrabat": "Sofyan Amrabat",
    "Sofjan Amrabat": "Sofyan Amrabat",
    "Solanke": "Dominic Solanke",
    "Soler": "Carlos Soler",
    "Solere": "Carlos Soler",
    "Son": "Heung-min Son",
    "Sorlot": "Sorlot",
    "Sottile": "Sottile",
    "Southampton": "Southampton FC",
    "Sporting": "Sporting CP",
    "Spurs": "Tottenham Hotspur",
    "Stefan Baiczetich": "Stefan Bajcetic",
    "Stefan Bycetic": "Stefan Bajcetic",
    "Stefan Ortega": "Stefan Ortega",
    "Stefano Pioli": "Stefano Pioli",
    "Stel": "Stel",
    "Sterling": "Raheem Sterling",
    "Strasbourg": "RC Strasbourg",
    "Strikers": "Strikers",
    "Strudel": "Strudel",
    "Stuttgart": "VfB Stuttgart",
    "Subimendi": "Subimendi",
    "Sufa Moucoco": "Sofa Moukoko",
    "Sugawara": "Daichi Sugawara",
    "Suley": "Suley",
    "Summerville": "Samuel Summerville",
    "Sunderland": "Sunderland AFC",
    "Sverre": "Sverre",
    "Sverre Nipan": "Sverre Nypan",
    "Takekubo": "Takekubo",
    "Tamia Abram": "Tamia Abram",
    "Tammy Abrams": "Tammy Abraham",
    "Tant Alexander-Arnold": "Trent Alexander-Arnold",
    "Tarky": "Tarky",
    "Tassari": "Tassari",
    "Tau": "Tau",
    "Telegraph": "Telegraph",
    "Tema Dobbic": "Tema Dobbic",
    "Ten Haag": "Erik ten Hag",
    "Tenag": "Erik ten Hag",
    "Tenhag": "Erik ten Hag",
    "Tenhug": "Erik ten Hag",
    "Tenso Albes": "Tenso Alves",
    "Teo Hernández": "Theo Hernández",
    "Terzino": "Terzino",
    "Teta": "Teta",
    "Thiago Mota": "Thiago Motta",
    "Thiago Motta": "Thiago Motta",
    "Thibaut Courtois": "Thibaut Courtois",
    "Thomas": "Thomas",
    "Thomas Arauco": "Ronald Araújo",
    "Thomas Araujo": "Ronald Araújo",
    "Thomas Frank": "Thomas Frank",
    "Thomas Müller": "Thomas Müller",
    "Thomas Patti": "Thomas Patti",
    "Thomas Raoucho": "Raoucho",
    "Thomas Tuchel": "Thomas Tuchel",
    "Tia Gomotta": "Thiago Motta",
    "Tiago Motta": "Thiago Motta",
    "Tibu Kurtua": "Thibaut Courtois",
    "Tijani": "Tijani Reinders",
    "Tijani Reinders": "Tijani Reinders",
    "Tijsani Reinders": "Tijani Reinders",
    "Tom": "Tom",
    "Tominey": "Tominey",
    "Tomori": "Fikayo Tomori",
    "Tonali": "Sandro Tonali",
    "Tony": "Tony",
    "Tony Rudiger": "Antonio Rüdiger",
    "Torino": "Torino FC",
    "Tosina": "Tosina",
    "Tottenham": "Tottenham Hotspur",
    "Trent": "Trent Alexander-Arnold",
    "Trent Alexander": "Trent Alexander-Arnold",
    "Trent Alexander Arnault": "Trent Alexander-Arnold",
    "Trent Alexander Arnold": "Trent Alexander-Arnold",
    "Trent Alexander-Arlo": "Trent Alexander-Arnold",
    "Trent Alexander-Arnold": "Trent Alexander-Arnold",
    "Trent Alexander-Rambel": "Trent Alexander-Arnold",
    "Trevo Chaloba": "Trevo Chalobah",
    "Trevo Chalobar": "Trevo Chalobah",
    "Tribal Chaloba": "Trevo Chalobah",
    "Trippier": "Kieran Trippier",
    "Tuchel": "Thomas Tuchel",
    "Tugarte": "Ugarte",
    "Tyrell": "Tyrell Malacia",
    "Tyrell Malasia": "Tyrell Malacia",
    "Ugarte": "Ugarte",
    "Ugarte Ugarte": "Ugarte",
    "Ugarthe": "Ugarte",
    "Ugo Viana": "Ugo Viana",
    "Unai": "Unai Emery",
    "Unai Emery": "Unai Emery",
    "Unaiemeri": "Unai Emery",
    "United": "Manchester United",
    "Ure Yemery": "Unai Emery",
    "Usair Mazrawi": "Usama Mazraoui",
    "Usman Dembélé": "Ousmane Dembélé",
    "Valencia": "Valencia CF",
    "Valentin Carboni": "Valentin Carboni",
    "Valladolid": "Real Valladolid",
    "Van Dijk": "Virgil van Dijk",
    "Van Nisterloy": "Rud van Nistelrooy",
    "Vanderson": "Vanderson",
    "Varan": "Varane",
    "Varela": "Varela",
    "Vaya": "Vaya",
    "Veers": "Veers",
    "Verkusten": "VfL Wolfsburg",
    "Vicenza": "Vicenza",
    "Victor": "Victor",
    "Victor Boniface": "Victor Boniface",
    "Victor Diocres": "Victor Osimhen",
    "Victor Giocares": "Victor Osimhen",
    "Victor Gjoklis": "Victor Osimhen",
    "Victor Gjokores": "Victor Osimhen",
    "Victor Onosimen": "Victor Osimhen",
    "Victor Osiman": "Victor Osimhen",
    "Victor Ossiman": "Victor Osimhen",
    "Victor Ossimen": "Victor Osimhen",
    "Victor Ozi Men": "Victor Osimhen",
    "Victor Oziman": "Victor Osimhen",
    "Victor Ozimán": "Victor Osimhen",
    "Victor Ozyman": "Victor Osimhen",
    "Victor Ozymen": "Victor Osimhen",
    "Victor Ozzyman": "Victor Osimhen",
})
corrections.update({
    "Victor Rosiman": "Victor Osimhen",
    "Victor Rosimand": "Victor Osimhen",
    "Victor Rosimann": "Victor Osimhen",
    "Victor Rosimen": "Victor Osimhen",
    "Victor Zivane": "Victor Osimhen",
    "Victor ozimen": "Victor Osimhen",
    "Victoros": "Victor Osimhen",
    "Vierce": "Veers",
    "Viktor Gjokoress": "Victor Osimhen",
    "Viktor Osumen": "Victor Osimhen",
    "Viktor Ozimán": "Victor Osimhen",
    "Vila": "Villa",
    "Villa": "Aston Villa",
    "Villarreal": "Villarreal CF",
    "Villas-Bosch": "Villas-Boas",
    "Vincent Company": "Vinícius Júnior",
    "Vinic": "Vinícius",
    "Vinicius": "Vinícius Júnior",
    "Vinicius Jr": "Vinícius Júnior",
    "Virgil": "Virgil van Dijk",
    "Virgil van Dijk": "Virgil van Dijk",
    "Virts": "Virgil van Dijk",
    "Vito Reis": "Vito Roque",
    "Vito Reyes": "Vito Roque",
    "Vito Roque": "Vito Roque",
    "Vitor": "Vitor Roque",
    "Vitor Osimem": "Victor Osimhen",
    "Vitor Reis": "Vito Roque",
    "Vitor Roque": "Vito Roque",
    "Vitorroca": "Vito Roque",
    "Vittigna": "Vittigna",
    "WANBISACA": "Wan-Bissaka",
    "Wahi": "Wahi",
    "Waleitihad": "Waleitihad",
    "Walker": "Kyle Walker",
    "Wambisaka": "Wan-Bissaka",
    "Wanbisaka": "Wan-Bissaka",
    "Waneri": "Wan-Bissaka",
    "Watkins": "Ollie Watkins",
    "Weirce": "Veers",
    "Wesley": "Wesley",
    "Wesley Fofana": "Wesley Fofana",
    "West End": "West Ham United",
    "West Ham": "West Ham United",
    "West Hem": "West Ham United",
    "Westem": "West Ham United",
    "Westemar": "West Ham United",
    "Wilhelm Esteval": "William Saliba",
    "Will": "Will",
    "William": "William",
    "William Estebao": "William Saliba",
    "William Estevo": "William Saliba",
    "William Pacho": "William Pacho",
    "William Saliba": "William Saliba",
    "Williams": "Williams",
    "Willy": "Willy",
    "Willy Cambuala": "Willy Cabala",
    "Willy Cambuola": "Willy Cabala",
    "Winger": "Winger",
    "Wirth": "Wirth",
    "Wojciech Chesny": "Wojciech Szczęsny",
    "Wolverhampton": "Wolverhampton Wanderers",
    "Wolves": "Wolverhampton Wanderers",
    "Wombisaka": "Wan-Bissaka",
    "Wunderberg": "Wunderberg",
    "Xabi": "Xabi Alonso",
    "Xabi Alonso": "Xabi Alonso",
    "Xavi": "Xavi Hernández",
    "Xavi Simons": "Xavi Simons",
    "Yano Black": "Yannick Black",
    "YouTube": "YouTube",
    "Ypswich Town": "Ipswich Town",
    "Yuma Bah": "Yuma",
    "Zaghi": "Zaghi",
    "Zaleschi": "Zaleschi",
    "Zavarni": "Zavarni",
    "Zed": "Zed",
    "Zegrova": "Zegrova",
    "Zered": "Zerede",
    "Zeredue": "Zerede",
    "Zierze": "Zierze",
    "Zilder": "Zilder",
    "Zirte": "Zirte",
    "Zirz": "Zirz",
    "Zivane": "Victor Osimhen",
    "Zubi Mendi": "Mikel Zubimendi",
    "Zubimendi": "Mikel Zubimendi",
    "Zvonsi Football Club": "Zvonsi Football Club",
    "araujo": "Ronald Araújo",
    "arsenal": "Arsenal FC",
    "aston villa": "Aston Villa",
    "atleti": "Atletico Madrid",
    "atletico": "Atletico Madrid",
    "atletico Madrid": "Atletico Madrid",
    "bar mount": "FC Barcelona",
    "barca": "FC Barcelona",
    "barcelo": "FC Barcelona",
    "barça": "FC Barcelona",
    "benjamin": "Benjamin",
    "brahindias": "Brahim Diaz",
    "broya": "Broja",
    "byron": "Byron",
    "carateta": "Careteta",
    "casemiro": "Casemiro",
    "champions league": "UEFA Champions League",
    "chelsea": "Chelsea FC",
    "chiusa": "Chiusa",
    "danie olmo": "Dani Olmo",
    "de Bala": "De Bala",
    "de Rossi": "Daniele De Rossi",
    "deligt": "Matthijs de Ligt",
    "hug": "Hug",
    "iCAP Athens": "ICAP Athens",
    "isak": "Alexander Isak",
    "john duran": "John Duran",
    "jonathan": "Jonathan",
    "juventus": "Juventus FC",
    "lucacu": "Lucaku",
    "matchday": "Matchday",
    "may United": "Manchester United",
    "may united": "Manchester United",
    "men city": "Manchester City",
    "napoli": "Napoli",
    "nashworth": "Nashworth",
    "nico gonzalez": "Nico González",
    "osiman": "Osimhen",
    "ozyman": "Osimhen",
    "paul victor": "Paul Victor",
    "proton VPN": "Proton VPN",
    "romero lucacu": "Romero Lukaku",
    "ronaldo": "Cristiano Ronaldo",
    "ronaldo araujo": "Ronald Araújo",
    "sancho": "Jadon Sancho",
    "sander berge": "Sander Berge",
    "schesco": "Schesco",
    "secu conne": "Secu Conne",
    "shallow": "Shallow",
    "sporting": "Sporting CP",
    "the Alps Sociedad": "Real Sociedad",
    "the Brazilian Federation": "Brazilian Football Confederation",
    "the Champions League": "UEFA Champions League",
    "the Premier League": "Premier League",
    "the Rash Ward": "The Rash Ward",
    "the Red Bull Group": "Red Bull Group",
    "the Santa Bex": "Santa Bex",
    "the Saudi Pro League": "Saudi Pro League",
    "the Serie A": "Serie A",
    "united": "Manchester United",
    "van Dijk": "Virgil van Dijk",
    "van Nesterloy": "Rud van Nistelrooy",
    "victor osiman": "Victor Osimhen",
    "Álvarez": "Álvaro Álvarez",
    "Álvaro Carreras": "Álvaro Carreras",
    "Álvaro Fernández": "Álvaro Fernández",
})

def correct_json_files(directory="./video_data"):
    files = [f for f in os.listdir(directory) if f.endswith(".json")]
    total = len(files)

    updated_files = 0
    skipped_files = 0
    start = 0

    for i, filename in enumerate(files, 1):
        path = os.path.join(directory, filename)
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)

            players = data.get("extracted_players_info", {}).get("players", {})
            new_players = {}
            changed = False

            for key, value in players.items():
                corrected_key = corrections.get(key, key)
                if corrected_key != key:
                    logging.info(f"Renamed '{key}' -> '{corrected_key}' in {filename}")
                    changed = True
                new_players[corrected_key] = value

            if changed:
                data["extracted_players_info"]["players"] = new_players
                with open(path, "w", encoding="utf-8") as f:
                    json.dump(data, f, indent=2, ensure_ascii=False)
                updated_files += 1
            else:
                skipped_files += 1

        except Exception as e:
            logging.error(f"Failed to process {filename}: {e}")

        show_progress(i, total, start, description="Updating JSON files")

    logging.info(f"Update complete: {updated_files} files updated, {skipped_files} skipped.")

correct_json_files()
